spring:
  application:
    name: customer-service
  datasource:
    username: postgres
    password: qwas123
    url: jdbc:postgresql://localhost:5432/practice1
  jpa:
    hibernate:
      ddl-auto: update