spring:
  application:
    name: product-service
  datasource:
    username: postgres
    password: qwas1234
    url: jdbc:postgresql://localhost:5432/practice1
  jpa:
    hibernate:
      ddl-auto: update